name: Visualize repo with diagram

on:
  workflow_dispatch: {}
  push:
    branches:
      - develop

jobs:
  visualize_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # ratchet:actions/checkout@v4.1.4
      - name: Update diagram
        uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85 # ratchet:githubocto/repo-visualizer@v0.9.1
        with:
          excluded_paths: ".github,.husky,.yarn"
